### ISSUE TITLE
Is it possible to change the image of the main button?

### ISSUE THREAD

**Issue by martinliu0** [kciter/KCFloatingActionButton#14]
As titled.

**Comment by sitefinitysteve** [comment]
Would be very interested in an API option this as well :)

**Comment by kciter** [comment]
Hello @martinliu0 
I'm planning to make it soon.
Thank you.

**Comment by kciter** [comment]
Hello @martinliu0, @sitefinitysteve.
I have updated this issue
Thanks.

**Comment by sitefinitysteve** [comment]
Awesome @kciter !  Thanks so much, love your implimentation!
