### ISSUE TITLE
Layout issues after application went to background

### ISSUE THREAD

**Issue by AnasMostefaoui** [kciter/KCFloatingActionButton#24]
Hello,
I'm using the KCFloatingActionButton (1.2.1)  with items that have only icons and no text.
Every thing work well, as long as the application stay at foreground : 
<img width="96" alt="screen shot 2016-03-23 at 21 28 48" src="https://cloud.githubusercontent.com/assets/1833498/14000016/78ff95e8-f13f-11e5-9ae5-5d17539d6aa6.png">

now if i go background (when i trigger [UIApplication sharedApplication] openURL: for exemple), wait few seconds, go back to the application from the application icon, this is the layout now : 
<img width="90" alt="screen shot 2016-03-23 at 21 28 59" src="https://cloud.githubusercontent.com/assets/1833498/14000059/b0aba982-f13f-11e5-90cd-cdbb4c66b3ad.png">

notice that the KCFloatingActionButtonItem's method : drawRect, get called when i try to go back to the application, but this time the frame value did change in this line of createCircleLayer method : 
`circleLayer.frame = CGRectMake(frame.size.width - size, 0, size, size)`

i did not find why the frame property chage it's value, but i got a work around to fix this issue : 
replace the precedent line of code : 
`circleLayer.frame = CGRectMake(frame.size.width - size, 0, size, size)`
by : 
`        let castParent : KCFloatingActionButton = superview as! KCFloatingActionButton;
        circleLayer.frame = CGRectMake(castParent.itemSize/2 - (size/2), 0, size, size)`
this give me a perfect centred item circle.

**Comment by kciter** [comment]
Hello @AnasMostefaoui.
Solved on 1.3.0 version. Thanks.
