### ISSUE TITLE
Vertical layout issues

### ISSUE THREAD

**Issue by AnasMostefaoui** [kciter/KCFloatingActionButton#25]
Hello,

i've noticed that the button y positions changed slightly after the first menu open, in the version  1.2.1 of the KCFloatingActionButton.
the following picture show the menu opened the first time since the view did apear : 
<img width="55" alt="screen shot 2016-03-23 at 22 00 49" src="https://cloud.githubusercontent.com/assets/1833498/14000726/c71eeb68-f142-11e5-98a5-acefbd576076.png">

closing the menu, then reopen it give the following result : 
<img width="56" alt="screen shot 2016-03-23 at 22 01 06" src="https://cloud.githubusercontent.com/assets/1833498/14000749/dede365a-f142-11e5-86de-b5abe4f8e4c2.png">
one can notice in the second picture, has the button items higher than the first one.

the code responsible for this issue is located in KCFloatingActionButton's open() method : 
`                item.frame.origin.y = -itemHeight
                item.layer.transform = CATransform3DMakeScale(0.4, 0.4, 1)`
inverse the order of the instruction, to fix this issue : 
`                item.layer.transform = CATransform3DMakeScale(0.4, 0.4, 1)
                item.frame.origin.y = -itemHeight`

**Comment by kciter** [comment]
Hello @AnasMostefaoui.
Solved on 1.3.0 version. Thanks.
