### ISSUE TITLE
Can't assign UIColor to the button color

### ISSUE THREAD

**Issue by HenriqueDoura** [kciter/KCFloatingActionButton#27]
I have a color and I'm trying to assign it as the button color. It's crashing right before the view with the button appears and the console says:
`2016-03-29 22:23:31.643 Homework[34702:2044491] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -CGColor not defined for the UIColor <UIPlaceholderColor: 0x100a1ada0>; need to first convert colorspace.'
*** First throw call stack:
(0x184700f5c 0x1992f7f80 0x184700ea4 0x18a07c824 0x100173ff8 0x10016df94 0x10016e098 0x189488b4c 0x189473bd4 0x189472df4 0x189454d00 0x1894549ec 0x18945407c 0x189453dd0 0x18944d4bc 0x1846b7c30 0x1846b59d4 0x1845e4de0 0x189cc40ac 0x189cbef44 0x100051eb8 0x199b228b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `
It points the crash to the class KCFloatingActionButton.swift line 433 and when you call that function in the same file, line 220. I'm sure the color I'm assigning is a UIColor.

**Comment by HenriqueDoura** [comment]
Fixed.

**Comment by kciter** [comment]
I'm sorry for my late reply.
I'm glad you solved well.

**Comment by HenriqueDoura** [comment]
No worries. Is there a way to put a sound when the floating button is
tapped? I've  alreay tried to use gesture recognizers, the function
touchesBegan to see if the user tapped on the fab.center, but none of them
worked.

Thanks in advance

Em quinta-feira, 31 de março de 2016, Lee Sun-Hyoup <
notifications@github.com> escreveu:

**Comment by kciter** [comment]
Hello, @HenriqueDoura 
I added delegate func in 1.3.1 version. Check it up please.
Thanks.

**Comment by HenriqueDoura** [comment]
Hello, thanks for adding it. I was only able to test it today, and it
doesn't seem to be working. I've already inherited from the delegate
protocol and added the functions, but nothing that I'm putting inside the
functions is working.

Em sexta-feira, 1 de abril de 2016, Lee Sun-Hyoup <notifications@github.com>
escreveu:

**Comment by HenriqueDoura** [comment]
Totally my bad, it's working fine. I forgot to actually call the delegate!
Another question: why are the item icons in the center? If I put a big
image it still is centered and it doesn't look so cool

On Sun, Apr 3, 2016 at 8:03 PM, Henrique Dourado <henriquendourado@gmail.com

**Comment by kciter** [comment]
Hello, @HenriqueDoura 
If you want to put a big image, you should resize your image.
And if you don't like the centered image, you can use to `imageOffset` in `KCFloatingActionButtonItem`.
Thanks :)
