### ISSUE TITLE
Title is not tappable anymore

### ISSUE THREAD

**Issue by madelman** [kciter/KCFloatingActionButton#28]
Hi,

since the commit with the new animation types:

https://github.com/kciter/KCFloatingActionButton/commit/95f78ef81e8872d184aceaf2be21d1b9c1f5bdef

the titles are not tappable anymore, when you press a title it justs closes the layer instead of executing the action.

Thanks

**Comment by kciter** [comment]
Hello, @madelman 
I fixed it in 1.3.1 version. Check it up please.
Thanks.
