### ISSUE TITLE
Can you add image offset to button items?

### ISSUE THREAD

**Issue by Ying1986** [kciter/KCFloatingActionButton#29]
![image](https://cloud.githubusercontent.com/assets/6648212/14280124/6c52db60-fb63-11e5-9c93-4ba5cdbb91bf.png)

In above image, some item is fine, but other is not(horizontal).
I need to offset image on button item.

Thank you.

**Comment by kciter** [comment]
Hello, @madelman 
I added `imageOffset` property in `KCFloatingActionButtonItem` at 1.3.2 version. Check it up please.
Thanks.

**Comment by Ying1986** [comment]
Thank you,
