### ISSUE TITLE
Add target as UIButton to KCFloatingActionButton

### ISSUE THREAD

**Issue by navishshanbog** [kciter/KCFloatingActionButton#3]
Hello Author, 

This is definatley not an issue, but I have a question to ask as I am in the learning stage. I would like to know how I can add action to the parent KCFloatingActionButton.
I want to add something like
"button.addTarget(self, action: "buttonAction:", forControlEvents: UIControlEvents.TouchUpInside)"
to both KCFloatingActionButton and to the KCFloatingActionButtonItem.

Could you please guide me.

Many thanks in advance,

Regards,

**Comment by kciter** [comment]
Hello @navishshanbog,

Unfortunately, `KCFloatingActionButton` is not `UIButton`. So, you cannot use `addTarget` method.
But, if you want to add touch event to `KCFloatingActionButton`, it is available through `UITapGestureRecogonizer`.
Below is the sample code.

**Swift**
```swift
let tapGesture = UITapGestureRecognizer(target: self, action: "handleSingleTap:")
self.fab.addGestureRecognizer(tapGesture)

// Event handling method
func handleSingleTap(recognizer: UITapGestureRecognizer) {
  // Do stuff here...
}
```

**Objective-C**
```objc
UITapGestureRecognizer *tapGesture = 
  [[UITapGestureRecognizer alloc] initWithTarget:self 
                                          action:@selector(handleSingleTap:)];
[self.fab addGestureRecognizer:tapGesture];

// Event handling method
- (void)handleSingleTap:(UITapGestureRecognizer *)recognizer {
  // Do stuff here...
}
```

Best regards,
