### ISSUE TITLE
Swift and Xcode Version

### ISSUE THREAD

**Issue by dreloong** [kciter/KCFloatingActionButton#30]
The new syntax `#selector` in KCFloatingActionButton.swift only works with Swift 2.2+. So the version of Swift and Xcode in README might need to be changed.

Actually is it possible to make it compatible with older versions of Swift? Since many users haven't update Xcode to the latest version.

**Comment by kciter** [comment]
Good point, I create `swift2.0` branch and fix `README.md` in master branch.
https://github.com/kciter/KCFloatingActionButton/tree/swift2.0

Thanks.

**Comment by dreloong** [comment]
@kciter Cool, thanks!
