### ISSUE TITLE
issue on TableViewController

### ISSUE THREAD

**Issue by iceman201** [kciter/KCFloatingActionButton#32]
- I setup in tableview controller， scroll down. The FloatingButton position didnt update.

**Comment by kciter** [comment]
Do you have any screenshot?

**Comment by iceman201** [comment]
just close it i fixed that issue

**Comment by kciter** [comment]
I'm sorry for my late reply. 😢 
Thank you.

**Comment by iceman201** [comment]
nononono mate, all good. it's pretty good framework btw

**Comment by Rashesh-Bosamiya** [comment]
If you have solved can you show the solution?
