### ISSUE TITLE
Plus icon layout distorted

### ISSUE THREAD

**Issue by sakshiGoel26** [kciter/KCFloatingActionButton#34]
Steps to reproduce the issue:

1. Open floating button.
2. Close the application.
3. Open Camera & click a picture.
4. Open the app again

You will find that image inside floating button is distorted from its actual frame.

**Comment by kciter** [comment]
I can't reproduce. 😢 
Do you have any screenshot?

**Comment by kuyazee** [comment]
for me it happens when you rotate the phone

the plus of the floating button goes outside the button

but when you shake your phone (rotate to side and stand it up back again) it returns to normal

**Comment by kciter** [comment]
Hello, @kuyazee 
I can't reproduce. 😢
Do you have any screenshot?
Sorry

**Comment by kciter** [comment]
Hi guys
I fixed bugs, and update podspec 1.4.0.
😄
