### ISSUE TITLE
when adding a new item image it doesnt fill the whole circle!...how can i fix that?

### ISSUE THREAD

**Issue by AmrSayedAhmed** [kciter/KCFloatingActionButton#40]

**Comment by kciter** [comment]
What do you mean?
Do you have any screenshot?

**Comment by yigitserin** [comment]
I have a similar issue. See this:
![ss](https://cloud.githubusercontent.com/assets/8073308/16731276/df012b4a-477f-11e6-862e-f9a4850abbb9.png)

Context: I used the same icons with the same method and it worked perfectly fine. However, I needed to make the buttons smaller since it wouldn't fit some device screens. So I made the following changes:

        if UIScreen.mainScreen().bounds.height < 600 {
            fab.itemSpace = 8
            fab.itemSize = 36
            fab.size = 40
        }

However, changing itemSize parameter break the image centering. How do I make sure images stay centered when I change the itemSize?

**Comment by kciter** [comment]
Hello guys
This issue may be same as [Issue 44](https://github.com/kciter/KCFloatingActionButton/issues/44).
Check it out please. 😄

**Comment by yigitserin** [comment]
Tried the solution there but didn't worked for me. When I change the itemSize, it does not calculate the center correctly.

**Comment by kciter** [comment]
It really my mistake. I fixed it.

**Comment by yigitserin** [comment]
Thanks, altough I can't seem to get the latest version from cocoapods. When I do `pod search KCFloatingActionButton` it shows the latest version is 1.3.4.

**Comment by kciter** [comment]
@yigitserin 
```
$ pod search KCFloatingActionButton

-> KCFloatingActionButton (1.3.6)
   Floating Action Button for iOS
   pod 'KCFloatingActionButton', '~> 1.3.6'
   - Homepage: https://github.com/kciter/KCFloatingActionButton
   - Source:   https://github.com/kciter/KCFloatingActionButton.git
   - Versions: 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.1, 1.0.0 [master repo]
```
https://github.com/CocoaPods/Specs/blob/master/Specs/KCFloatingActionButton/1.3.6/KCFloatingActionButton.podspec.json
🤔

**Comment by allaire** [comment]
This broke `fab.buttonImage`, now my icon appears out of the fab

**Comment by kciter** [comment]
Hello, @allaire 
I've update to version `1.3.7`.
Check it out please. 😄

**Comment by yigitserin** [comment]
It worked for me, thanks! Also had to update my pod repository for new versions to appear.

**Comment by kciter** [comment]
Good :)
This issue is closed.

**Comment by allaire** [comment]
Worked, thanks!
