### ISSUE TITLE
Speeding up the Pop animation

### ISSUE THREAD

**Issue by yigitserin** [kciter/KCFloatingActionButton#43]
Hello there,

Is it possible to increase the buttons pop speed? Currently it takes about 1 second to all buttons to appear. I would like to decrease that.

Thanks for the work!

**Comment by kciter** [comment]
I'm sorry for my late reply.
Now you can not. If you want, pull-request to me.

**Comment by yigitserin** [comment]
Thanks for the reply, I managed to speed up to animation by reducing the delay to 0.05 from 0.1 here:

    private func popAnimationWithOpen() {
        var itemHeight: CGFloat = 0
        var delay = 0.0
        for item in items {
            if item.hidden == true { continue }
            itemHeight += item.size + itemSpace
            item.layer.transform = CATransform3DMakeScale(1, 1, 1)
            item.frame.origin.y = -itemHeight
            item.layer.transform = CATransform3DMakeScale(0.4, 0.4, 1)
            UIView.animateWithDuration(0.3, delay: delay,
                                       usingSpringWithDamping: 0.55,
                                       initialSpringVelocity: 0.3,
                                       options: [.CurveEaseInOut], animations: { () -> Void in
                                        item.layer.transform = CATransform3DMakeScale(1, 1, 1)
                                        item.alpha = 1
                }, completion: nil)
            
            delay += 0.05
        }
    }
