### ISSUE TITLE
Icons in KCFloatingActionButtonItem distorted

### ISSUE THREAD

**Issue by tylerjames** [kciter/KCFloatingActionButton#44]
Hey, I noticed that some of my icons seemed a bit squished. I checked in the code and found this:

    /**
     Item's icon image view.
     */
    var _iconImageView: UIImageView? = nil
    public var iconImageView: UIImageView {
        get {
            if _iconImageView == nil {
                _iconImageView = UIImageView(frame: CGRectMake(0, 0, 21, 23))
                //                _iconImageView = UIImageView(frame: CGRectMake(frame.size.width - size, 0, 21, 23))
                _iconImageView?.center = CGPointMake(size/2, size/2) + imageOffset
                _iconImageView?.contentMode = UIViewContentMode.ScaleToFill
                addSubview(_iconImageView!)
            }
            return _iconImageView!
        }
    }

In this line:
`_iconImageView = UIImageView(frame: CGRectMake(0, 0, 21, 23))`
you can see that the image view is not a square.

And in this line:
`_iconImageView?.contentMode = UIViewContentMode.ScaleToFill`
... the content mode is set to .ScaleToFill which does not maintain the image aspect ratio.

**Solution**
If you set it to .ScaleAspectFill it will maintain the ratio and not distort the images.

**Comment by kciter** [comment]
I fixed it.
From:
```swift
_iconImageView = UIImageView(frame: CGRectMake(0, 0, 21, 23))
_iconImageView?.contentMode = UIViewContentMode.ScaleToFill
```

To:
```swift
_iconImageView = UIImageView(frame: CGRectMake(0, 0, 25, 25))
_iconImageView?.contentMode = UIViewContentMode.ScaleAspectFill
```

Thank you!
