### ISSUE TITLE
Question or enhancement 

### ISSUE THREAD

**Issue by Kam21** [kciter/KCFloatingActionButton#5]
Hi There,

I was wondering how i can move the menu around without changing the following padding..
var padding: CGFloat = 14

I wanted to move the menu from bottom just Y-Axis only.  I having some issue adding KCFloatingActionButton with iAd.  The Floating Menu is going behind  iAdd.

Thanks.

**Comment by kciter** [comment]
Hello, @Kam21
If you want to move the menu Y-Axis only, you can move it easily by `paddingY` variable.

Thanks.
