### ISSUE TITLE
need to change titlecolor

### ISSUE THREAD

**Issue by kuyazee** [kciter/KCFloatingActionButton#50]
I've seen the source code and it's quite easy to implement. :) 

I just put this here so you may see it.  

btw. thanks for the library bro

**Comment by kciter** [comment]
Hello, @kuyazee 
I've update to v1.3.7.
You can use `KCFloatingActionButton.itemTitleColor` and `KCFloatingActionButtonItem.titleColor`.

Thank you for your contribution. :smile:
