### ISSUE TITLE
Position should be sticked when scrolling UITableView.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [kciter/KCFloatingActionButton#52]
I have a UITableView with 2 section and 5 rows in each sections.

I have added floating button in viewDidLoad method.

Output showing button at end of view, but not on the tableView's end of row.

**Comment by kciter** [comment]
Hello, @Rashesh-Bosamiya 
KCFAB's default position is bottom-right of superview.
If you want KCFAB's position set to tableView's end of row, you should calculate position.
