### ISSUE TITLE
How to call function in handler

### ISSUE THREAD

**Issue by ImranIB** [kciter/KCFloatingActionButton#53]
I want to call function in item handler. On respective item click I want to perform an action. Any help?

 let item = KCFloatingActionButtonItem()
 item.icon = UIImage(named: "red_bar")
 item.title = "RECORD"
 item.handler = handler
 item.titleColor = UIColor(red: 1, green: 0.8, blue: 0, alpha: 1.0)

**Comment by kciter** [comment]
Hello, @ImranIB 
You can assign to handler.
```swift
item.handler = { item in
     // ...
}
```

**Comment by ImranIB** [comment]
Thanks @kciter. issue resolved

**Comment by kciter** [comment]
Good
This issue is closed. 😄
