### ISSUE TITLE
Change Icon on tapped

### ISSUE THREAD

**Issue by ImranIB** [kciter/KCFloatingActionButton#54]
![simulator screen shot jul 25 2016 5 11 32 pm](https://cloud.githubusercontent.com/assets/10369328/17100924/f956928a-528a-11e6-8db2-2b12af6eded8.png)

I want to change that floating button icon on click. Any help.  I tried to change that in the function but nothing happened.
```swift
func KCFABOpened(fab: KCFloatingActionButton) {
        print("FAB Opened")
        fab.buttonImage = UIImage(named: "cross_multiple")
}
```

**Comment by kciter** [comment]
Hello, @ImranIB 
I'm too late.
I fixed bugs, and update podspec 1.4.0.
😄
