### ISSUE TITLE
change X and Y position of KCbutton

### ISSUE THREAD

**Issue by SirSamShaw** [kciter/KCFloatingActionButton#59]
Hello, I am using the KC button programmatically and right now it is partly covering the location of a banner ad. How could I solve this by programmatically moving it up? Thank you for all assistance!

**Comment by kciter** [comment]
Hello, @SirSamShaw 
You can use KCFAB's `paddingX` and `paddingY`.
😄

**Comment by SirSamShaw** [comment]
Hello, @kciter I could not locate this, could you give an example??

**Comment by SirSamShaw** [comment]
False alarm found it :) Thank you @kciter 👍

**Comment by kciter** [comment]
Good! 😄
