### ISSUE TITLE
Can I use two floating buttons?

### ISSUE THREAD

**Issue by nkhaja** [kciter/KCFloatingActionButton#60]
Hi 

I tried creating two floating (one on the left and right of the screen) buttons using this API. 

However, if I create two flaotingButtons, clicking on either triggers only one menu ( the last one added). I want the press to only open the menu corresponding to the button clicked.

**Comment by kciter** [comment]
Hello, @nkhaja 
It's a unexpected bug. :cry:
I fixed the bug and you can use `friendlyTap` property in `v1.4.3`.
Your problem will be solved when `friendlyTap` as `false`.

**Comment by nkhaja** [comment]
Works perfectly, thank you! :)
