### ISSUE TITLE
filling up the custom button background

### ISSUE THREAD

**Issue by SamuelShaw** [kciter/KCFloatingActionButton#61]
I am wanting to change the floating buttons to a custom 1 with a blue background. the image is round and is 1024 x 1024. When I place it into the code and run, the image is small and not filling up the default white background. How could I over come this?
![screen shot 2016-08-11 at 12 31 41 pm](https://cloud.githubusercontent.com/assets/14863465/17596490/9bce4fb2-5fbf-11e6-8be1-c2baebd98ad0.png)

**Comment by kciter** [comment]
You can use the `KCFloatingActionButtonItem.buttonColor`.
Below is simple example.
```swift
let item = KCFloatingActionButtonItem()
item.buttonColor = UIColor.blueColor()
item.title = "Custom item"
fab.addItem(item: item)
```

**Comment by SirSamShaw** [comment]
ok @kciter  the problem is if I change the background color, the icon itself is still small unlike the icons that come with the KFAB example project. Would this have to do with the icon not being in an asset set? I noticed the default ones are in a set of three inside an asset set called icon (1, @2x, and @3x).

**Comment by kciter** [comment]
@SirSamShaw 
Can you give me your icons? I need re-produce.

**Comment by SirSamShaw** [comment]
yes thank you 
![add_visitor_btn](https://cloud.githubusercontent.com/assets/17830626/17708911/0893606c-63b5-11e6-9c47-4d5e4e934e0c.png)
![msg_btn](https://cloud.githubusercontent.com/assets/17830626/17708912/0895b006-63b5-11e6-853a-d789132200b0.png)
![srch_btn](https://cloud.githubusercontent.com/assets/17830626/17708910/0892ff64-63b5-11e6-85a9-5872c7825ee9.png)

**Comment by kciter** [comment]
KCFABItem's icon image size is 25x25 point. So, remove the your icons background color and shadow. And you should resize image to 25x25 point.

**Comment by SamuelShaw** [comment]
ah ok Thank you!, do I need to place them in an asset set or can I just
place them in by name directly in code after I resize them??

**Comment by kciter** [comment]
@SamuelShaw 
Once again,
KCFAB's item is already applied shadow and background color.
You can make using the design tool a transparent background and resize them.
Then, you place them in an asset set and add item in code.
```swift
var fab = KCFloatingActionButton()
fab.itemButtonColor = UIColor.blueColor() // Choose your color.
fab.addItem("title", icon: UIImage(named: "icName"))
// ...
```

**Comment by SirSamShaw** [comment]
ok, thank you!

**Comment by preethichimerlaInspy** [comment]
Hi @kciter , @SirSamShaw  how can I change the main fab icon image ?
