### ISSUE TITLE
Xcode 8  and modern Swift syntax

### ISSUE THREAD

**Issue by tylerjames** [kciter/KCFloatingActionButton#63]
The Xcode 8 GM build is out now and opening up a project with this library included will cause Xcode to prompt you to convert to either Swift 2.3 or Swift 3.0 (preferred) syntax. If you choose not to then your project will no longer build. 

This library will need to be updated to modern syntax before it can be used with Xcode 8.

**Comment by kciter** [comment]
Hello @tylerjames 
KCFAB support to `Swift 3.0` from version `2.0.0`.

```
use_frameworks!
pod "KCFloatingActionButton", "~> 2.0.0"
# Or
# pod "KCFloatingActionButton", :git => 'https://github.com/kciter/KCFloatingActionButton.git', :tag => '2.0.0'
# pod "KCFloatingActionButton", :git => 'https://github.com/kciter/KCFloatingActionButton.git', :branch => 'swift3.0'
```

**Comment by tylerjames** [comment]
Thanks! 
I tried updating it to 3.0 myself but Xcode kept complaining about the drawLayer code and I don't know Swift well enough to know what it was whining about.

**Comment by kciter** [comment]
Is it solved? :)
Swift 3.0 had a lot of changes. I need to learn again. 😢

**Comment by tylerjames** [comment]
Sorry, I haven't tried running it yet. But if the 3.0 branch compiles on your end that's at least farther than I made it. Was pretty annoying to learn that Xcode 8 won't even compile Swift 2.2 code. The transition to 2.3 is much easier but only seems worth it in the short term.

**Comment by kciter** [comment]
Okay. 😄 But, if you want Swift 2.3 code. I'll make `swift2.3` branch tomorrow.
