### ISSUE TITLE
Changing Title

### ISSUE THREAD

**Issue by recoilnetworks** [kciter/KCFloatingActionButton#64]
I am trying to change the title of a menu item when it has been tapped however, when I do this, the new title is no longer centered with the icon, it's higher. Let me know if you need a screenshot. I have tried everything I can think of to find a way around this but to no avail. Thank you.

**Comment by kciter** [comment]
Hello @recoilnetworks .
Can you give me your screenshot? 😄

**Comment by recoilnetworks** [comment]
The "Show Predators" and "Show Zones" is before tapping them and the "Hide Predators" and "Hide Zones" is after.

![2016-09-10 01 12 17](https://cloud.githubusercontent.com/assets/18174749/18409018/cf67bca0-76f3-11e6-8437-87a55e030ec3.png)
![2016-09-10 01 12 22](https://cloud.githubusercontent.com/assets/18174749/18409019/cf7eb4f0-76f3-11e6-8df1-f072c926f58a.png)
![2016-09-10 01 12 30](https://cloud.githubusercontent.com/assets/18174749/18409020/cf7f5c98-76f3-11e6-8336-a3fd25d32bbd.png)

**Comment by kciter** [comment]
Thank you! I'll check it. 😃

**Comment by kciter** [comment]
Hello @recoilnetworks 
I fixed issue. 😄 
```
pod 'KCFloatingActionButton', '1.4.4'
```

If you use to swift 3.0, use to `2.0.1`
```
pod 'KCFloatingActionButton', :git => 'https://github.com/kciter/KCFloatingActionButton.git', :tag => '2.0.1'
```

**Comment by recoilnetworks** [comment]
Thank you very much, you're awesome!
