### ISSUE TITLE
Changing Padding Doesn't Change Tap Point

### ISSUE THREAD

**Issue by recoilnetworks** [kciter/KCFloatingActionButton#65]
I am using your menu over a Google Map. In the lower right corner of the map is Google's My Location Button which, when tapped, will re-center the map on the user's current location. Because I need this icon and feature, I wanted to place the float menu button above Google's My Location Button however, when I do this and try to tap the Google My Location Button, it still opens the menu as of I tapped the menu button. Screenshot of positioning is attached. By the way, it does it no matter where the button is placed as long as it is directly above Google's My Location Button.

![img_2714](https://cloud.githubusercontent.com/assets/18174749/18576097/1a2c0158-7b93-11e6-8974-9732aefc675d.jpg)
![img_2715](https://cloud.githubusercontent.com/assets/18174749/18576099/1ccee5f6-7b93-11e6-887a-fe390f27d84c.jpg)

**Comment by kciter** [comment]
Hello :)
Your problem will be solved when `friendlyTap` property as `false`.

**Comment by recoilnetworks** [comment]
Very nice! Thank you again!
