### ISSUE TITLE
fabs moves in tableview

### ISSUE THREAD

**Issue by StevenArmandLee** [kciter/KCFloatingActionButton#67]
I'm putting the fab in tableviewcontroller and when I scroll the table, the button also moves. is there a way to fix this?

thanks.

**Comment by StevenArmandLee** [comment]
I found the solution by using this

```
override func scrollViewDidScroll(_ scrollView: UIScrollView) {
        floatingActionButton.paddingY = 10-scrollView.contentOffset.y
    }
```

however I have not really tried it with a long list of cells, so far it works perfectly however if anyone has a perfect solutions, please share it :)

**Comment by kciter** [comment]
Hello @StevenArmandLee 
I'm sorry for being late.

If you can possible, use the below.
```swift
override func viewDidLoad() {
    KCFABManager.defaultInstance().show()
}

override func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
    if velocity.y > 0 {
        KCFABManager.defaultInstance().hide()
    } else {
        KCFABManager.defaultInstance().show()
    }
}

Or I added `sticky` property in version `2.1.0`.
```swift
override func viewDidLoad() {
    super.viewDidLoad();
    fab.sticky = true // sticking to parent UIScrollView(or UITableView, UICollectionView)
    view.addSubview(fab)
}

override func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
    if velocity.y > 0 {
        fab.isHidden = true
    } else {
        fab.isHidden = false
    }
}
```

**Comment by StevenArmandLee** [comment]
@kciter btw I noticed that the button is transparent when I use it in a view controller which contain table view

while it is a solid color at tableviewcontroller

how do I make all of them a solid color? I made sure my alpha is 1

**Comment by StevenArmandLee** [comment]
@kciter ok so the color is correct is just that somehow the cell separator is in front of the button. and when we click the button it will go to the front of the cell separator. tried to put it to the most front and it does not work also

any solution?
