### ISSUE TITLE
Status bar on top is changing

### ISSUE THREAD

**Issue by kalvish21** [kciter/KCFloatingActionButton#68]
I put the status bar on top to light color (so the text is white). For some reason adding this floating button is making it black.

**Comment by kciter** [comment]
Hello @kalvish21 
Please give me your screenshot. 😄

**Comment by kalvish21** [comment]
![simulator screen shot sep 20 2016 8 52 32 pm](https://cloud.githubusercontent.com/assets/2179704/18697247/3b51ab6e-7f74-11e6-98d6-b3453b15bb95.png)

The status bar at top was set to white, when I remove the button the text is white, when I put it htere the text is black.

**Comment by artemmihelson** [comment]
The same issue for me, adding UIWindow dependent floating button changes Navigation controllers' navigation bar bar style to white (font color is black).

**Comment by kciter** [comment]
You can use `KCFABViewController` in `2.1.2` version.
```swift
// Example
KCFABManager.defaultInstance().fabController.statusBarStyle = UIStatusBarStyle.lightContent
KCFABManager.defaultInstance().fabController.setNeedsStatusBarAppearanceUpdate()
```

**Comment by AlecsRosa** [comment]
You can simply add this code on your ViewController. 

```
extension FloatyViewController {
    
    override open var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
}

```
