### ISSUE TITLE
Unable to use with Xcode 8

### ISSUE THREAD

**Issue by uday-mshr** [kciter/KCFloatingActionButton#72]
Hi 
I am Unable to use this in Xcode 8 And Swift 3

**Comment by kciter** [comment]
Hello @uday-mshr 
What is your `KCFloatingActionButton` Pod version?

**Comment by uday-mshr** [comment]
1.0.1

**Comment by kciter** [comment]
Do this
```
# Podfile
use_frameworks!
pod "KCFloatingActionButton", "~> 2.1.0"
```

**Comment by uday-mshr** [comment]
![screen shot 2016-09-24 at 11 40 31 am](https://cloud.githubusercontent.com/assets/19321534/18806480/c89bac34-824b-11e6-8179-066c42c31bd0.png)

**Comment by kciter** [comment]
@uday-mshr execute `pod repo update` before `pod install`
