### ISSUE TITLE
Create multiple KCFAB

### ISSUE THREAD

**Issue by jsonmat** [kciter/KCFloatingActionButton#73]
Hello there! How do I create multiple FABs with different positions in the screen?

Thanks.

**Comment by kciter** [comment]
Hello @jsonmat 
You can use the `paddingX` and `paddingY` for different position.

**Comment by jsonmat** [comment]
Thank you for your quick reply. I changed some code so my first KCFAB is showing in bottom left. Is it possible to have the second KCFAB to be in bottom right?

**Comment by kciter** [comment]
Sure you can! But bottom left's KCFAB can't show item's title. KCFAB doesn't provide yet. 😢
