### ISSUE TITLE
Swift3 version is not supported for iOS 8 ?

### ISSUE THREAD

**Issue by sundarsan** [kciter/KCFloatingActionButton#75]
Is there any specific resolution for backward compatibility to iOS 8 ?

**Comment by kciter** [comment]
I will fix the minimum version to iOS 8 later.

**Comment by SagarUnagar** [comment]
Same requirement! @kciter when you are going to finish it?

**Comment by kciter** [comment]
Now, support to iOS 8 in `2.1.2`

**Comment by OrkhanAlikhanov** [comment]
Hey @kciter, Readme.md is misleading. podspec file defines ios version 8 but readme says 9
