### ISSUE TITLE
Moving the FAB out of tab bar

### ISSUE THREAD

**Issue by dpstart** [kciter/KCFloatingActionButton#78]
I added a UITabBar to my view, so now the FAB is partially covered by the bar.

I tried to change the frame of the FAB, but it stays in the same place.

**Comment by Phontana** [comment]
I am having the same issue. What I tried as a workaround is to add the FAB with a custom frame using the `initWithFrame:` method, so it floats above the tab bar. However, this gives me a new issue: when showing the keyboard, the FAB is moved up, but when hiding the keyboard the FAB stays in place.

**Comment by kciter** [comment]
Hello,
You can use `paddingY` property in `KCFloatingActionButton`.
