### ISSUE TITLE
Change buttonColor on handler

### ISSUE THREAD

**Issue by helderalvesoliveira** [kciter/KCFloatingActionButton#87]
Hi, everyone 
i want change my button color on handler, but doesn´t change:

(...)

        item.title = "Talvez"
        item.icon = UIImage(named: "neutral")
        item.handler = { item in
            itembuttonColor =  UIColor.gray
            
        }
(...)

It´s possible to give me some help ?

Thanks for your time.

**Comment by Lufthummel** [comment]
I'm facing the same issue. Any solution available?

**Comment by kciter** [comment]
Hello, solution here.
```
item.handler = { item in
    item.buttonColor = UIColor.green
    item.setNeedsDisplay()
}
```

**Comment by keziia22** [comment]
still cannot :( using item.setNeedsDisplay()

**Comment by keziia22** [comment]
Better u code like this i think 
let fab = KCFloatingActionButton()
        let item = KCFloatingActionButtonItem()
        item.buttonColor = UIColor.blue
        item.title = "Custom item"
        item.handler = {item in
            self.performSegue(withIdentifier: "segueToAnother", sender: self)
        }
        fab.addItem(item: item)

**Comment by a598799539** [comment]
I want to change `fab.buttonColor` and `fab.itemButtonColor` at the same time.  It will only change `buttonColor` if `fab.setNeedsDisplay()`. And I try

```swift
fab.items.forEachEnumerated({ (index, item) in
                item.setNeedsDisplay()
            })
```

, but it does not work.

**Comment by a598799539** [comment]
I try: 
```swift
fab.items.forEachEnumerated({ (index, item) in
                item.buttonColor = MyColor
                item.setNeedsDisplay()
            })
```
That's work.

**Comment by kciter** [comment]
Good :)
