### ISSUE TITLE
Not open up KCFloatingActionButton when user taps tabBar item below the button

### ISSUE THREAD

**Issue by zoufishanmehdi** [kciter/KCFloatingActionButton#88]
I adjusted the padding of KCFloatingActionButton to make it appear slightly above the tabBar. However, tapping a tabBar item makes the button open as well. I wanted to disable opening the button when a tabBar item below the button is tapped (or tapping below the button in general). Any ideas?

**Comment by Dayyoung** [comment]
in my case :

    func initFloatingButton(_ main: UIView , _ tab: UITabBar) {
        
        fab = KCFloatingActionButton()
        
        fab?.buttonImage = UIImage(named: "ic_search_white")
        fab?.buttonColor = UIColor(r: 182, g: 102, b: 255, a: 1.0)
        fab?.paddingY = -300
        fab?.animationSpeed = 0
        fab?.sticky = true
        
        //for hide
        
        let gesture = UITapGestureRecognizer(target: self, action: #selector(self.closeAndGoSearch(_:)))
        
        fab?.addGestureRecognizer(gesture)
        
        main.addSubview(fab!)
        main.bringSubview(toFront: fab!)
        main.bringSubview(toFront: tab)
        
    }
    
    func hideFloatingButton()
    {
        fab?.paddingY = -300
    
    }
    
    func showFloatingButton()
    {
        fab?.paddingY = 60
        
    }

**Comment by Dayyoung** [comment]
bringSubview() is solved keyword. Adding gesture is for click event.

**Comment by kciter** [comment]
Hello, You can use the `friendlyTap` property.
ref: #47, #65
