### ISSUE TITLE
Opening the main button then rotating the screen causes plus to go off-screen

### ISSUE THREAD

**Issue by Brown-amazingness** [kciter/KCFloatingActionButton#9]
If you press the plus then rotate the screen while the handlers are showing then the plus moves off the center and to the right corner of the default blue circle. I think setting the center would be the best way to address this

**Comment by kciter** [comment]
Hello @Brown-amazingness 
I'm sorry for my late reply.
Thank you for your idea. I will refer to it.

**Comment by kciter** [comment]
It fixed.
