### ISSUE TITLE
Fab falls apart when device rotated

### ISSUE THREAD

**Issue by Nagesh-Chandan** [kciter/KCFloatingActionButton#90]
_Orientation change when FAB menu is opened will mess up the UI_

**Comment by BrankoIlic** [comment]
![screen shot 2017-02-13 at 11 43 12 am](https://cloud.githubusercontent.com/assets/12830018/22880251/c41c16ca-f1e1-11e6-87e2-599ff623feee.png)
![screen shot 2017-02-13 at 11 43 30 am](https://cloud.githubusercontent.com/assets/12830018/22880265/d0778472-f1e1-11e6-8d98-2029f6f5212e.png)

**Comment by BrankoIlic** [comment]
I have fixed the issue by adding FAB to the UIScrollView.

**Comment by kciter** [comment]
Hello.
It is an unexpected bug.
If you send a PR, I will merge.

**Comment by BrankoIlic** [comment]
I have fixed it in my app, it is not fix in the KCFloatingActionButton lib.

**Comment by kciter** [comment]
Ah, okay :)
