### ISSUE TITLE
Labels To come at the Right hand Side of the Fab Menu.

### ISSUE THREAD

**Issue by iAviatorJose** [kciter/KCFloatingActionButton#91]

**Comment by kciter** [comment]
Hello @iAviatorJose.
Can you give me your screenshot? 😄

**Comment by iAviatorJose** [comment]
![img_5959](https://cloud.githubusercontent.com/assets/8208627/22882666/33ef8574-f212-11e6-885e-552fbd7a2330.jpg)

Here it is i want the labels to come on right side in RTL support.

**Comment by kciter** [comment]
Hello, @iAviatorJose.
This feature is not yet available in the library.
If you send a PR, I will merge.
Thank you.

**Comment by iAviatorJose** [comment]
@kciter  thanks

**Comment by kciter** [comment]
It adds to `ToDo`.
