### ISSUE TITLE
Place KCFloatingActionButton in a specific location 

### ISSUE THREAD

**Issue by hamz250** [kciter/KCFloatingActionButton#93]
Im trying to place the KCFloatingActionButton on the right button corner of the screen like it's shown on your Demo but I m getting it on the middle right of the screen.
Is there any way to specify the desirable location ?
I m using : 
self.view.addSubview(fab)

**Comment by kciter** [comment]
Hello, @hamz250 
Check your view size or fab's paddingY.

**Comment by hamz250** [comment]
Thank you @kciter
