### ISSUE TITLE
KCFloatingActionButton itemsize set 56px, BUT KCFloatingActionButtonItem touch bounds is still 42px.

### ISSUE THREAD

**Issue by acadia3000** [kciter/KCFloatingActionButton#94]

**Comment by kciter** [comment]
안녕하세요. 한국분이신 것 같아서 한국말로 남기겠습니다.
제가 `2.1.2` 버전에서 테스트했을 때에는 잘 작동하는데 혹시 스크린샷을 올려주실 수 있을까요? :)
감사합니다.

**Comment by acadia3000** [comment]
@kciter 네 안녕하세요~ 한국어로 쓸려다가.. 
만들어 주신 KCFloatingActionButton 잘 사용하고 있습니다. 감사합니다 ^^

아이템들이 56px 로 잘 보여집니다. 
그러나, 아이템의 상단, 중단 부분 이외에 하단 부분을 터치하게 되면 그냥 닫히는 이슈입니다.

왠지 KCFloatingActionButton itemSize = 56 로 실제 item 의 bounds 변경이 안되어서 
hitTest 에서 tapArea 를 인식하지 못하는것 같습니다.

`
let floatingButtonSize: CGFloat = 56
let padding: CGFloat = 16
        
floatingButton.sticky = true
floatingButton.paddingX = padding
floatingButton.paddingY = padding
floatingButton.size = floatingButtonSize
floatingButton.itemSize = floatingButtonSize
floatingButton.itemSpace = 15
`

![simulator screen shot 2017 2 20 7 14 57](https://cloud.githubusercontent.com/assets/4263361/23121045/3a757044-f7a2-11e6-9193-acea24252ee1.png)

**Comment by kciter** [comment]
@acadia3000 안녕하세요. 이상하게도 샘플에서 테스트했을 때에는 잘 동작합니다. ㅠㅠ 혹시 라이브러리 버전이 어떻게 되시나요? 다음은 제가 테스트한 코드입니다.
```swift
let item = KCFloatingActionButtonItem()
item.buttonColor = UIColor.blue
item.circleShadowColor = UIColor.red
item.titleShadowColor = UIColor.blue
item.title = "Custom item"
item.handler = { item in
    item.buttonColor = UIColor.green
    item.setNeedsDisplay()
}
        
fab.addItem(title: "I got a title")
fab.addItem("I got a icon", icon: UIImage(named: "icShare"))
fab.addItem("I got a handler", icon: UIImage(named: "icMap")) { item in
    let alert = UIAlertController(title: "Hey", message: "I'm hungry...", preferredStyle: .alert)
    alert.addAction(UIAlertAction(title: "Me too", style: .default, handler: nil))
    self.present(alert, animated: true, completion: nil)
}
fab.addItem(item: item)
fab.fabDelegate = self
        
fab.size = 56
fab.itemSize = 56
fab.itemSpace = 15
fab.paddingX = 16
fab.paddingY = 16
fab.sticky = true
        
self.view.addSubview(fab)
```

**Comment by acadia3000** [comment]
@kciter  안녕하세요~ 주신 코드로 샘플 만들어 보았습니다.
Installing KCFloatingActionButton (2.1.2) << 코코아팟으로 받은 버전.

아래 샘플코드 추가함. 이상하게 제 테스트 코드에서는 여전히 이슈가 있습니다. ㅠㅠ
감사합니다~

[FloatingButtonSample.zip](https://github.com/kciter/KCFloatingActionButton/files/789095/FloatingButtonSample.zip)


![simulator screen shot 2017 2 21 1 46 47](https://cloud.githubusercontent.com/assets/4263361/23151248/c86b0db0-f83c-11e6-9d77-cfdfef01052e.png)

**Comment by kciter** [comment]
@acadia3000 아 죄송합니다 ㅜㅜ 예전에 수정했던 문제인데 제가 업데이트를 안했었네요. 다른 이슈 해결하느라 추가된 기능 포함해서 2.2.0 업데이트했습니다.
![image](https://cloud.githubusercontent.com/assets/3623695/23152645/993a6a2c-f846-11e6-8c1f-f655abdbf73f.png)
```
pod 'KCFloatingActionButton', '~> 2.2.0'
```
업데이트하시면 해결되실거에요. 버그 제보 감사합니다! :)

**Comment by acadia3000** [comment]
@kciter 업댓 감사드립니다. 잘 됩니다.  close 시킬게요~
좋은 하루 되세요~ ^^
