### ISSUE TITLE
Size of Item-Icon not the same size as Item

### ISSUE THREAD

**Issue by MightyAlienDwarf** [kciter/KCFloatingActionButton#95]
I create a FAB with two items. The main button itself works well. It has an image which is the same size as the button. But the images for my item are not as big as the items. There's kind of a padding around it, which doesn't look good.

![bildschirmfoto 2017-02-20 um 13 00 17](https://cloud.githubusercontent.com/assets/25899846/23124443/5f65fa5c-f76d-11e6-888d-18f77cec7a6d.png)

Could please somebody tell me how to fix it??

My viewDidLoad looks as follows:

    override func viewDidLoad() {
        super.viewDidLoad()
        
        NotificationCenter.default.addObserver(self, selector: #selector(updateView(note:)), name: NSNotification.Name(rawValue: "update_view"), object: nil)
        
        let backgroundImage = UIImageView(frame: UIScreen.main.bounds)
        backgroundImage.image = UIImage(named: "logo")
        backgroundImage.alpha = 0.3
        backgroundImage.contentMode = .scaleAspectFit
        tableView.backgroundView = backgroundImage
        
        tableView.separatorStyle = .none
        
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 33
        
        tableView.allowsMultipleSelectionDuringEditing = false
        

        if createFAB == true {
            createFloatingActionButton()
            view.layoutIfNeeded()
        }

    }

The method for creating the FAB:

       func createFloatingActionButton() {

        KCFABManager.defaultInstance().getButton().buttonImage = UIImage(named: "FAB_ham_beige")
        
        KCFABManager.defaultInstance().getButton().addItem(icon: UIImage(named: "FAB_add_red"), handler: { item in
            KCFABManager.defaultInstance().hide()
            self.performSegue(withIdentifier: "CreateRum", sender: nil)
        })
        
        KCFABManager.defaultInstance().getButton().addItem(icon: UIImage(named:"FAB_sort_red"), handler: { item in
            item.itemBackgroundColor = Colors.DarkBrown
            item.buttonColor = Colors.DarkBrown
            KCFABManager.defaultInstance().hide()
            
            let popOverVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "sortSelectionID") as! SortSelectionViewController
            popOverVC.delegate = self
            popOverVC.view.frame = UIScreen.main.bounds
            
            if let delegate = UIApplication.shared.delegate as? AppDelegate {
                if let window = delegate.window {
                    delegate.popup = popOverVC
                    window.addSubview(popOverVC.view)
                }
            }
        })
        
        KCFABManager.defaultInstance().show()
    }

**Comment by kciter** [comment]
I added `imageSize` property in `KCFloatingActionButtonItem` at `2.2.0` version.
Please update library. :)
```
pod 'KCFloatingActionButton', '~> 2.2.0'
```

**Comment by MightyAlienDwarf** [comment]
Thank you! :o)

**Comment by takasurazeem** [comment]
Sorry to bump it but setting the size and there's still a little distortion. 
<img width="77" alt="image" src="https://user-images.githubusercontent.com/2876680/189760321-18514e61-0e36-408e-909e-1ad1903bb284.png">
